# Generated by Django 3.2.8 on 2021-11-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richtexteditor', '0002_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
